//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalancaDaVidaAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BalancaDaVidaAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [
        ///    {
        ///        &quot;ID&quot;: &quot;1&quot;,
        ///        &quot;nome&quot;: &quot;Arroz&quot;,
        ///        &quot;descricao&quot;: &quot;integral, cozido&quot;,
        ///        &quot;umidade&quot;: &quot;70,1&quot;,
        ///        &quot;energia_kcal&quot;: &quot;124&quot;,
        ///        &quot;proteína_g&quot;: &quot;2,6&quot;,
        ///        &quot;colesterol_mg&quot;: &quot;NA&quot;,
        ///        &quot;carboidrato_g&quot;: &quot;25,8&quot;,
        ///        &quot;fibra_Alimentar_g&quot;: &quot;2,7&quot;,
        ///        &quot;calcio_mg&quot;: &quot;5&quot;,
        ///        &quot;ferro_mg&quot;: &quot;0,3&quot;,
        ///        &quot;sodio_mg&quot;: &quot;1&quot;,
        ///        &quot;potassio_mg&quot;: &quot;75&quot;,
        ///        &quot;vitaminac_mg&quot;: &quot;&quot;
        ///    },
        ///    {
        ///        &quot;ID&quot;: &quot;2&quot;,
        ///        &quot;nome&quot;: &quot;Arroz&quot;,
        ///        &quot;descricao&quot;:  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string JsonForApI {
            get {
                return ResourceManager.GetString("JsonForApI", resourceCulture);
            }
        }
    }
}
